// Generated by Kiro
import { ApiProperty } from '@nestjs/swagger';
import { IsString, IsNotEmpty, MinLength, MaxLength } from 'class-validator';

export class CreateRoomDto {
  @ApiProperty({
    description: 'User input text for the room',
    example: 'Create a spooky story about a haunted mansion',
    minLength: 1,
    maxLength: 5000,
  })
  @IsString()
  @IsNotEmpty()
  @MinLength(1)
  @MaxLength(5000)
  inputText: string;

  @ApiProperty({
    description: 'User ID (from JWT)',
    example: 'user-123',
  })
  @IsString()
  @IsNotEmpty()
  userId: string;
}
