// Generated by Kiro - Express server for StoryAgent
import express, { Request, Response, NextFunction } from 'express';
import cors from 'cors';
import { StoryService } from './story.service';
import { AgentMetrics } from '@hauntedai/shared';
import {
  StoryGenerationRequest,
  StoryGenerationResponse,
  HealthCheckResponse,
  ErrorResponse,
} from './types';

export class StoryAgentServer {
  private app: express.Application;
  private storyService: StoryService;
  private metrics: AgentMetrics;
  private port: number;

  constructor(apiKey: string, port: number = 3002) {
    this.app = express();
    this.port = port;
    this.storyService = new StoryService(apiKey);
    this.metrics = new AgentMetrics('story');
    this.setupMiddleware();
    this.setupRoutes();
    this.setupErrorHandling();
  }

  private setupMiddleware(): void {
    this.app.use(cors());
    this.app.use(express.json());
    this.app.use(express.urlencoded({ extended: true }));

    // Request logging and metrics
    this.app.use((req: Request, res: Response, next: NextFunction) => {
      const startTime = Date.now();
      console.log(`[${new Date().toISOString()}] ${req.method} ${req.path}`);
      
      res.on('finish', () => {
        const duration = (Date.now() - startTime) / 1000;
        this.metrics.recordHttpRequest(req.method, req.path, res.statusCode, duration);
      });
      
      next();
    });
  }

  private setupRoutes(): void {
    // Health check endpoint
    this.app.get('/health', async (req: Request, res: Response) => {
      try {
        const openaiHealthy = await this.storyService.checkHealth();

        const response: HealthCheckResponse = {
          status: openaiHealthy ? 'ok' : 'error',
          service: 'story-agent',
          timestamp: new Date().toISOString(),
          openai: {
            connected: openaiHealthy,
          },
        };

        res.status(openaiHealthy ? 200 : 503).json(response);
      } catch (error) {
        const response: HealthCheckResponse = {
          status: 'error',
          service: 'story-agent',
          timestamp: new Date().toISOString(),
          openai: {
            connected: false,
          },
        };
        res.status(503).json(response);
      }
    });

    // Story generation endpoint
    this.app.post('/generate', async (req: Request, res: Response, next: NextFunction) => {
      const startTime = Date.now();
      try {
        const request: StoryGenerationRequest = {
          input: req.body.input,
          userId: req.body.userId,
          roomId: req.body.roomId,
        };

        console.log(`Generating story for input: "${request.input?.substring(0, 50)}..."`);

        const response: StoryGenerationResponse = await this.storyService.generateStory(request);

        const duration = (Date.now() - startTime) / 1000;
        this.metrics.recordExecution('story', 'success', duration);

        console.log(
          `Story generated successfully (${response.metadata.wordCount} words)`
        );

        res.status(200).json(response);
      } catch (error) {
        const duration = (Date.now() - startTime) / 1000;
        this.metrics.recordExecution('story', 'failure', duration);
        this.metrics.recordFailure('story', error.name || 'UnknownError');
        next(error);
      }
    });

    // Metrics endpoint
    this.app.get('/metrics', async (req: Request, res: Response) => {
      try {
        const metrics = await this.metrics.getMetrics();
        res.set('Content-Type', this.metrics.getContentType());
        res.send(metrics);
      } catch (error) {
        res.status(500).json({ error: 'Failed to get metrics' });
      }
    });

    // Root endpoint
    this.app.get('/', (req: Request, res: Response) => {
      res.json({
        service: 'story-agent',
        version: '1.0.0',
        status: 'running',
        endpoints: {
          health: 'GET /health',
          generate: 'POST /generate',
          metrics: 'GET /metrics',
        },
      });
    });
  }

  private setupErrorHandling(): void {
    // 404 handler
    this.app.use((req: Request, res: Response) => {
      const error: ErrorResponse = {
        error: 'Not Found',
        message: `Route ${req.method} ${req.path} not found`,
        statusCode: 404,
        timestamp: new Date().toISOString(),
      };
      res.status(404).json(error);
    });

    // Global error handler
    this.app.use((err: Error, req: Request, res: Response, next: NextFunction) => {
      console.error('Error:', err);

      const statusCode = (err as any).statusCode || 500;
      const error: ErrorResponse = {
        error: err.name || 'Internal Server Error',
        message: err.message || 'An unexpected error occurred',
        statusCode,
        timestamp: new Date().toISOString(),
      };

      res.status(statusCode).json(error);
    });
  }

  public start(): void {
    this.app.listen(this.port, () => {
      console.log(`🎃 StoryAgent service running on port ${this.port}`);
      console.log(`📍 Health check: http://localhost:${this.port}/health`);
      console.log(`📍 Generate story: POST http://localhost:${this.port}/generate`);
    });
  }

  public getApp(): express.Application {
    return this.app;
  }
}
