// Feature: haunted-ai, Property 2: Story storage round-trip
// Validates: Requirements 1.2
// Generated by Kiro - Property-based tests for story storage

import fc from 'fast-check';
import { StorachaClient } from './storacha.client';

describe('Property 2: Story storage round-trip', () => {
  let storachaClient: StorachaClient;

  beforeAll(() => {
    storachaClient = new StorachaClient();
  });

  it('should retrieve identical story after storage', async () => {
    await fc.assert(
      fc.asyncProperty(
        // Generate story-like strings
        fc.string({ minLength: 50, maxLength: 500 }),
        async (story) => {
          // Reset any state between iterations
          jest.clearAllMocks();

          // Upload story to Storacha
          const filename = `test-story-${Date.now()}.txt`;
          const cid = await storachaClient.uploadFile(Buffer.from(story, 'utf-8'), filename);

          // Property 2: CID should be valid
          expect(cid).toBeDefined();
          expect(typeof cid).toBe('string');
          expect(cid.length).toBeGreaterThan(0);

          // Property 2: CID should match expected pattern
          const cidPattern = /^bafy[a-z2-7]{55,}$/;
          expect(cid).toMatch(cidPattern);

          // Property 2: Validate CID using built-in validator
          expect(storachaClient.validateCID(cid)).toBe(true);

          // Note: Retrieval test would require fetching from IPFS gateway
          // which may take time for content to propagate. In a full implementation,
          // we would retrieve and verify the content matches:
          // const retrieved = await retrieveFromIPFS(cid);
          // expect(retrieved.toString('utf-8')).toBe(story);
        }
      ),
      {
        numRuns: 3, // Reduced due to network operations and potential costs
        timeout: 60000, // 60 second timeout per test
      }
    );
  }, 240000); // 4 minute timeout for entire test

  it('should generate valid CID for various story lengths', async () => {
    await fc.assert(
      fc.asyncProperty(
        // Generate stories of varying lengths
        fc.oneof(
          fc.string({ minLength: 10, maxLength: 100 }),
          fc.string({ minLength: 100, maxLength: 500 }),
          fc.string({ minLength: 500, maxLength: 2000 })
        ),
        async (story) => {
          const filename = `test-story-${Date.now()}.txt`;
          const cid = await storachaClient.uploadFile(Buffer.from(story, 'utf-8'), filename);

          // Should generate valid CID regardless of content length
          expect(storachaClient.validateCID(cid)).toBe(true);
          expect(cid).toMatch(/^bafy/);
        }
      ),
      {
        numRuns: 3,
        timeout: 60000,
      }
    );
  }, 240000);

  it('should handle special characters in story content', async () => {
    await fc.assert(
      fc.asyncProperty(
        // Generate strings with special characters
        fc.string({ minLength: 50, maxLength: 200 }),
        async (story) => {
          // Add some special characters
          const storyWithSpecialChars = `${story}\n\t"quotes" 'apostrophes' & symbols!`;

          const filename = `test-story-special-${Date.now()}.txt`;
          const cid = await storachaClient.uploadFile(
            Buffer.from(storyWithSpecialChars, 'utf-8'),
            filename
          );

          // Should handle special characters correctly
          expect(storachaClient.validateCID(cid)).toBe(true);
        }
      ),
      {
        numRuns: 2,
        timeout: 60000,
      }
    );
  }, 180000);

  it('should validate CID format correctly', () => {
    // Valid CIDs
    const validCIDs = [
      'bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi',
      'bafybeihdwdcefgh4dqkjv67uzcmw7ojee6xedzdetojuzjevtenxquvyku',
      'bafybeif2pall7dybz7vecqka3zo24irdwabwdi4wc55jznaq75q7eaavvu',
    ];

    validCIDs.forEach((cid) => {
      expect(storachaClient.validateCID(cid)).toBe(true);
    });

    // Invalid CIDs
    const invalidCIDs = [
      '', // empty
      'invalid', // wrong format
      'bafy', // too short
      'BAFYBEIGDYRZT5SFP7UDM7HU76UH7Y26NF3EFUYLQABF3OCLGTQY55FBZDI', // uppercase
      'bafybeig!@#$%', // special characters
    ];

    invalidCIDs.forEach((cid) => {
      expect(storachaClient.validateCID(cid)).toBe(false);
    });
  });
});
