// Generated by Kiro - Storacha client for StoryAgent
import { create } from '@web3-storage/w3up-client';
import type { Client } from '@web3-storage/w3up-client';

export class StorachaClient {
  private client: Client | null = null;
  private readonly maxRetries = 3;
  private readonly initialDelay = 2000;
  private readonly backoffMultiplier = 2;

  /**
   * Initialize Storacha client
   */
  async initialize(): Promise<void> {
    if (this.client) {
      return; // Already initialized
    }

    try {
      console.log('Initializing Storacha client...');
      this.client = await create();
      console.log('Storacha client initialized successfully');
    } catch (error) {
      console.error('Failed to initialize Storacha client:', error);
      throw error;
    }
  }

  /**
   * Upload file to Storacha with retry logic
   * @param buffer - File content as Buffer
   * @param filename - Name of the file
   * @returns CID string
   */
  async uploadFile(buffer: Buffer, filename: string): Promise<string> {
    return this.executeWithRetry(async () => {
      if (!this.client) {
        await this.initialize();
      }

      console.log(`Uploading file to Storacha: ${filename} (${buffer.length} bytes)`);

      // Create a File object from the buffer
      const file = new File([buffer], filename, { type: 'text/plain' });

      // Upload to Storacha
      const cid = await this.client!.uploadFile(file);

      const cidString = cid.toString();
      console.log(`File uploaded successfully with CID: ${cidString}`);

      return cidString;
    });
  }

  /**
   * Execute operation with exponential backoff retry logic
   */
  private async executeWithRetry<T>(operation: () => Promise<T>): Promise<T> {
    let lastError: Error | null = null;

    for (let attempt = 0; attempt < this.maxRetries; attempt++) {
      try {
        return await operation();
      } catch (error) {
        lastError = error as Error;

        if (attempt < this.maxRetries - 1) {
          const delay = Math.min(
            this.initialDelay * Math.pow(this.backoffMultiplier, attempt),
            30000
          );

          console.warn(
            `Upload failed (attempt ${attempt + 1}/${this.maxRetries}), ` +
              `retrying in ${delay}ms: ${lastError.message}`
          );

          await this.sleep(delay);
        }
      }
    }

    console.error(`Upload failed after ${this.maxRetries} attempts: ${lastError?.message}`);
    throw lastError;
  }

  /**
   * Sleep utility for retry delays
   */
  private sleep(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }

  /**
   * Validate CID format
   */
  validateCID(cid: string): boolean {
    const cidPattern = /^bafy[a-z2-7]{55,}$/;
    return cidPattern.test(cid);
  }
}
