// Generated by Kiro - Type definitions for StoryAgent

export interface StoryGenerationRequest {
  input: string;
  userId?: string;
  roomId?: string;
}

export interface StoryGenerationResponse {
  story: string;
  cid: string;
  metadata: {
    wordCount: number;
    generatedAt: Date;
    model: string;
  };
}

export interface HealthCheckResponse {
  status: 'ok' | 'error';
  service: string;
  timestamp: string;
  openai: {
    connected: boolean;
  };
}

export interface ErrorResponse {
  error: string;
  message: string;
  statusCode: number;
  timestamp: string;
}
