// Generated by Kiro
import {
  Controller,
  Get,
  Post,
  Body,
  Param,
  UseGuards,
  Request,
  HttpCode,
  HttpStatus,
  Res,
} from '@nestjs/common';
import {
  ApiTags,
  ApiOperation,
  ApiResponse,
  ApiBearerAuth,
  ApiParam,
} from '@nestjs/swagger';
import { Response } from 'express';

import { JwtAuthGuard } from '../auth/guards/jwt-auth.guard';
import { JwtOrQueryAuthGuard } from '../auth/guards/jwt-or-query-auth.guard';

import { RoomsService } from './rooms.service';
import { SSEService } from './sse.service';
import { CreateRoomDto } from './dto/create-room.dto';

@ApiTags('rooms')
@Controller('rooms')
@ApiBearerAuth()
export class RoomsController {
  constructor(
    private readonly roomsService: RoomsService,
    private readonly sseService: SSEService,
  ) {}

  @Post()
  @UseGuards(JwtAuthGuard)
  @ApiOperation({ summary: 'Create new room' })
  @ApiResponse({
    status: 201,
    description: 'Room created successfully',
    schema: {
      properties: {
        id: { type: 'string' },
        ownerId: { type: 'string' },
        status: { type: 'string', enum: ['idle', 'running', 'done', 'error'] },
        inputText: { type: 'string' },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
        owner: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            username: { type: 'string' },
            did: { type: 'string' },
          },
        },
      },
    },
  })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  async create(@Body() createRoomDto: CreateRoomDto, @Request() req: any) {
    // Get user ID from JWT token
    const userId = req.user?.sub || req.user?.id;

    if (!userId) {
      throw new Error('User ID not found in token');
    }

    return this.roomsService.create({
      ...createRoomDto,
      userId,
    });
  }

  @Get()
  @UseGuards(JwtAuthGuard)
  @ApiOperation({ summary: 'Get all rooms for authenticated user' })
  @ApiResponse({
    status: 200,
    description: 'List of user rooms',
    schema: {
      type: 'array',
      items: {
        properties: {
          id: { type: 'string' },
          ownerId: { type: 'string' },
          status: { type: 'string' },
          inputText: { type: 'string' },
          createdAt: { type: 'string' },
          updatedAt: { type: 'string' },
          assets: { type: 'array' },
        },
      },
    },
  })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  async findAll(@Request() req: any) {
    const userId = req.user.sub;
    return this.roomsService.findByUser(userId);
  }

  @Get(':id')
  @UseGuards(JwtAuthGuard)
  @ApiOperation({ summary: 'Get room details by ID' })
  @ApiParam({ name: 'id', description: 'Room UUID' })
  @ApiResponse({
    status: 200,
    description: 'Room details',
    schema: {
      properties: {
        id: { type: 'string' },
        ownerId: { type: 'string' },
        status: { type: 'string' },
        inputText: { type: 'string' },
        createdAt: { type: 'string' },
        updatedAt: { type: 'string' },
        owner: { type: 'object' },
        assets: { type: 'array' },
      },
    },
  })
  @ApiResponse({ status: 404, description: 'Room not found' })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  async findOne(@Param('id') id: string) {
    return this.roomsService.findOne(id);
  }

  @Post(':id/start')
  @UseGuards(JwtAuthGuard)
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Start agent workflow for room' })
  @ApiParam({ name: 'id', description: 'Room UUID' })
  @ApiResponse({
    status: 200,
    description: 'Workflow started successfully',
    schema: {
      properties: {
        id: { type: 'string' },
        status: { type: 'string', example: 'running' },
        message: { type: 'string' },
      },
    },
  })
  @ApiResponse({ status: 404, description: 'Room not found' })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  async start(@Param('id') id: string) {
    return this.roomsService.startWorkflow(id);
  }

  @Get(':id/logs')
  @UseGuards(JwtOrQueryAuthGuard)
  @ApiOperation({ summary: 'Stream live logs for room via Server-Sent Events' })
  @ApiParam({ name: 'id', description: 'Room UUID' })
  @ApiResponse({
    status: 200,
    description: 'SSE stream of room logs',
    content: {
      'text/event-stream': {
        schema: {
          type: 'string',
          example: 'event: log\ndata: {"timestamp":"2024-01-01T00:00:00.000Z","agentType":"story","level":"info","message":"Starting story generation"}\n\n',
        },
      },
    },
  })
  @ApiResponse({ status: 404, description: 'Room not found' })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  async streamLogs(@Param('id') id: string, @Res() res: Response) {
    // Verify room exists
    await this.roomsService.findOne(id);

    // Create SSE connection
    await this.sseService.createConnection(id, res);
  }
}
