// Generated by Kiro
import { Module } from '@nestjs/common';

import { RoomsController } from './rooms.controller';
import { RoomsService } from './rooms.service';
import { RedisService } from './redis.service';
import { SSEService } from './sse.service';

@Module({
  controllers: [RoomsController],
  providers: [RoomsService, RedisService, SSEService],
  exports: [RoomsService, RedisService, SSEService],
})
export class RoomsModule {}
