// Generated by Kiro - Integration Tests
import { Test, TestingModule } from '@nestjs/testing';
import { NotFoundException } from '@nestjs/common';
import { RoomStatus } from '@prisma/client';

import { PrismaService } from '../../prisma/prisma.service';

import { RoomsService } from './rooms.service';

describe('RoomsService - Integration Tests', () => {
  let service: RoomsService;
  let prismaService: PrismaService;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        RoomsService,
        {
          provide: PrismaService,
          useValue: {
            room: {
              create: jest.fn(),
              findUnique: jest.fn(),
              findMany: jest.fn(),
              update: jest.fn(),
            },
          },
        },
      ],
    }).compile();

    service = module.get<RoomsService>(RoomsService);
    prismaService = module.get<PrismaService>(PrismaService);
  });

  describe('create', () => {
    it('should create a new room with idle status', async () => {
      const createRoomDto = {
        userId: 'user-123',
        inputText: 'Create a spooky story',
      };

      const mockRoom = {
        id: 'room-123',
        ownerId: 'user-123',
        status: RoomStatus.idle,
        inputText: 'Create a spooky story',
        createdAt: new Date(),
        updatedAt: new Date(),
        owner: {
          id: 'user-123',
          username: 'testuser',
          did: 'did:ethr:0x123',
        },
      };

      jest.spyOn(prismaService.room, 'create').mockResolvedValue(mockRoom as any);

      const result = await service.create(createRoomDto);

      expect(result).toEqual(mockRoom);
      expect(result.status).toBe(RoomStatus.idle);
      expect(prismaService.room.create).toHaveBeenCalledWith({
        data: {
          ownerId: createRoomDto.userId,
          inputText: createRoomDto.inputText,
          status: RoomStatus.idle,
        },
        include: {
          owner: {
            select: {
              id: true,
              username: true,
              did: true,
            },
          },
        },
      });
    });
  });

  describe('findOne', () => {
    it('should return room with assets', async () => {
      const mockRoom = {
        id: 'room-123',
        ownerId: 'user-123',
        status: RoomStatus.idle,
        inputText: 'Test input',
        createdAt: new Date(),
        updatedAt: new Date(),
        owner: {
          id: 'user-123',
          username: 'testuser',
          did: 'did:ethr:0x123',
        },
        assets: [],
      };

      jest.spyOn(prismaService.room, 'findUnique').mockResolvedValue(mockRoom as any);

      const result = await service.findOne('room-123');

      expect(result).toEqual(mockRoom);
      expect(prismaService.room.findUnique).toHaveBeenCalledWith({
        where: { id: 'room-123' },
        include: {
          owner: {
            select: {
              id: true,
              username: true,
              did: true,
            },
          },
          assets: {
            orderBy: {
              createdAt: 'asc',
            },
          },
        },
      });
    });

    it('should throw NotFoundException when room not found', async () => {
      jest.spyOn(prismaService.room, 'findUnique').mockResolvedValue(null);

      await expect(service.findOne('non-existent')).rejects.toThrow(NotFoundException);
      await expect(service.findOne('non-existent')).rejects.toThrow(
        'Room with ID non-existent not found'
      );
    });
  });

  describe('findByUser', () => {
    it('should return all rooms for a user', async () => {
      const mockRooms = [
        {
          id: 'room-1',
          ownerId: 'user-123',
          status: RoomStatus.done,
          inputText: 'Test 1',
          createdAt: new Date(),
          updatedAt: new Date(),
          assets: [],
        },
        {
          id: 'room-2',
          ownerId: 'user-123',
          status: RoomStatus.idle,
          inputText: 'Test 2',
          createdAt: new Date(),
          updatedAt: new Date(),
          assets: [],
        },
      ];

      jest.spyOn(prismaService.room, 'findMany').mockResolvedValue(mockRooms as any);

      const result = await service.findByUser('user-123');

      expect(result).toEqual(mockRooms);
      expect(result).toHaveLength(2);
      expect(prismaService.room.findMany).toHaveBeenCalledWith({
        where: { ownerId: 'user-123' },
        include: {
          assets: {
            select: {
              id: true,
              agentType: true,
              cid: true,
              createdAt: true,
            },
          },
        },
        orderBy: {
          createdAt: 'desc',
        },
      });
    });

    it('should return empty array when user has no rooms', async () => {
      jest.spyOn(prismaService.room, 'findMany').mockResolvedValue([]);

      const result = await service.findByUser('user-123');

      expect(result).toEqual([]);
      expect(result).toHaveLength(0);
    });
  });

  describe('startWorkflow', () => {
    it('should update room status to running', async () => {
      const mockRoom = {
        id: 'room-123',
        ownerId: 'user-123',
        status: RoomStatus.idle,
        inputText: 'Test input',
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      const mockUpdatedRoom = {
        ...mockRoom,
        status: RoomStatus.running,
        owner: {
          id: 'user-123',
          username: 'testuser',
          did: 'did:ethr:0x123',
        },
      };

      jest.spyOn(prismaService.room, 'findUnique').mockResolvedValue(mockRoom as any);
      jest.spyOn(prismaService.room, 'update').mockResolvedValue(mockUpdatedRoom as any);

      const result = await service.startWorkflow('room-123');

      expect(result.status).toBe(RoomStatus.running);
      expect(result.message).toBe('Workflow started successfully');
      expect(prismaService.room.update).toHaveBeenCalledWith({
        where: { id: 'room-123' },
        data: {
          status: RoomStatus.running,
          updatedAt: expect.any(Date),
        },
        include: {
          owner: {
            select: {
              id: true,
              username: true,
              did: true,
            },
          },
        },
      });
    });

    it('should throw NotFoundException when room not found', async () => {
      jest.spyOn(prismaService.room, 'findUnique').mockResolvedValue(null);

      await expect(service.startWorkflow('non-existent')).rejects.toThrow(NotFoundException);
    });
  });

  describe('updateStatus', () => {
    it('should update room status to done', async () => {
      const mockRoom = {
        id: 'room-123',
        ownerId: 'user-123',
        status: RoomStatus.running,
        inputText: 'Test input',
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      const mockUpdatedRoom = {
        ...mockRoom,
        status: RoomStatus.done,
      };

      jest.spyOn(prismaService.room, 'findUnique').mockResolvedValue(mockRoom as any);
      jest.spyOn(prismaService.room, 'update').mockResolvedValue(mockUpdatedRoom as any);

      const result = await service.updateStatus('room-123', RoomStatus.done);

      expect(result.status).toBe(RoomStatus.done);
    });

    it('should update room status to error', async () => {
      const mockRoom = {
        id: 'room-123',
        ownerId: 'user-123',
        status: RoomStatus.running,
        inputText: 'Test input',
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      const mockUpdatedRoom = {
        ...mockRoom,
        status: RoomStatus.error,
      };

      jest.spyOn(prismaService.room, 'findUnique').mockResolvedValue(mockRoom as any);
      jest.spyOn(prismaService.room, 'update').mockResolvedValue(mockUpdatedRoom as any);

      const result = await service.updateStatus('room-123', RoomStatus.error, 'Test error');

      expect(result.status).toBe(RoomStatus.error);
    });

    it('should throw NotFoundException when room not found', async () => {
      jest.spyOn(prismaService.room, 'findUnique').mockResolvedValue(null);

      await expect(service.updateStatus('non-existent', RoomStatus.done)).rejects.toThrow(
        NotFoundException
      );
    });
  });
});
