// Generated by Kiro
import { Controller, Get, Param } from '@nestjs/common';
import { ApiTags, ApiOperation, ApiResponse } from '@nestjs/swagger';
import { UsersService } from './users.service';

@ApiTags('users')
@Controller('users')
export class UsersController {
  constructor(private readonly usersService: UsersService) {}

  @Get(':did/balance')
  @ApiOperation({ summary: 'Get user token balance' })
  @ApiResponse({ status: 200, description: 'User balance' })
  @ApiResponse({ status: 404, description: 'User not found' })
  async getBalance(@Param('did') did: string) {
    // TODO: Implement get balance
    return { message: 'Get balance endpoint - to be implemented' };
  }

  @Get(':did/transactions')
  @ApiOperation({ summary: 'Get user transaction history' })
  @ApiResponse({ status: 200, description: 'Transaction history' })
  async getTransactions(@Param('did') did: string) {
    // TODO: Implement get transactions
    return { message: 'Get transactions endpoint - to be implemented' };
  }
}
