// Generated by Kiro
// Custom guard that accepts JWT from header OR query parameter
// Used for SSE endpoints where EventSource can't send custom headers

import { Injectable, ExecutionContext } from '@nestjs/common';
import { AuthGuard } from '@nestjs/passport';

@Injectable()
export class JwtOrQueryAuthGuard extends AuthGuard('jwt') {
  getRequest(context: ExecutionContext) {
    const request = context.switchToHttp().getRequest();
    
    // If token is in query parameter, move it to Authorization header
    // This allows the standard JWT strategy to work
    if (request.query?.token && !request.headers.authorization) {
      request.headers.authorization = `Bearer ${request.query.token}`;
    }
    
    return request;
  }
}
