// Generated by Kiro - Entry point for AssetAgent service
import dotenv from 'dotenv';
import { AssetAgentServer } from './server';

// Load environment variables
dotenv.config();

// Validate required environment variables
const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
const PORT = parseInt(process.env.PORT || '3003', 10);

if (!OPENAI_API_KEY) {
  console.error('❌ Error: OPENAI_API_KEY environment variable is required');
  process.exit(1);
}

// Create and start server
const server = new AssetAgentServer(OPENAI_API_KEY, PORT);
server.start();

// Handle graceful shutdown
process.on('SIGTERM', () => {
  console.log('SIGTERM signal received: closing HTTP server');
  process.exit(0);
});

process.on('SIGINT', () => {
  console.log('SIGINT signal received: closing HTTP server');
  process.exit(0);
});
