// Generated by Kiro - Type definitions for AssetAgent

export interface AssetGenerationRequest {
  story: string;
  storySummary?: string;
  userId?: string;
  roomId?: string;
}

export interface AssetGenerationResponse {
  imageCid: string;
  imageUrl?: string;
  metadata: {
    size: number;
    format: string;
    width: number;
    height: number;
    generatedAt: Date;
    model: string;
    provider?: string;
    prompt: string;
  };
}

export interface HealthCheckResponse {
  status: 'ok' | 'error';
  service: string;
  timestamp: string;
  openai: {
    connected: boolean;
  };
}

export interface ErrorResponse {
  error: string;
  message: string;
  statusCode: number;
  timestamp: string;
}
