// Generated by Kiro
import { Controller, Post, Body, Get, Param, Query, UseGuards } from '@nestjs/common';
import { ApiTags, ApiOperation, ApiResponse, ApiBearerAuth, ApiParam, ApiQuery } from '@nestjs/swagger';

import { JwtAuthGuard } from '../auth/guards/jwt-auth.guard';

import { TokensService } from './tokens.service';

@ApiTags('tokens')
@Controller()
export class TokensController {
  constructor(private readonly tokensService: TokensService) {}

  @Get('users/:did/balance')
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth()
  @ApiOperation({ summary: 'Get user token balance' })
  @ApiParam({ name: 'did', description: 'User DID' })
  @ApiResponse({
    status: 200,
    description: 'User token balance',
    schema: {
      properties: {
        userId: { type: 'string' },
        did: { type: 'string' },
        username: { type: 'string' },
        balance: { type: 'number' },
        transactionCount: { type: 'number' },
      },
    },
  })
  @ApiResponse({ status: 404, description: 'User not found' })
  async getBalance(@Param('did') did: string) {
    return this.tokensService.getBalance(did);
  }

  @Get('users/:did/transactions')
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth()
  @ApiOperation({ summary: 'Get user transaction history' })
  @ApiParam({ name: 'did', description: 'User DID' })
  @ApiQuery({ name: 'limit', required: false, type: Number })
  @ApiQuery({ name: 'offset', required: false, type: Number })
  @ApiResponse({ status: 200, description: 'Transaction history' })
  @ApiResponse({ status: 404, description: 'User not found' })
  async getTransactions(
    @Param('did') did: string,
    @Query('limit') limit?: number,
    @Query('offset') offset?: number
  ) {
    return this.tokensService.getTransactions(
      did,
      limit ? Number(limit) : undefined,
      offset ? Number(offset) : undefined
    );
  }

  @Post('tokens/reward')
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth()
  @ApiOperation({ summary: 'Reward user with tokens (internal)' })
  @ApiResponse({ status: 200, description: 'Tokens rewarded' })
  async reward(
    @Body()
    rewardDto: {
      userId: string;
      amount: number;
      reason: string;
      txHash?: string;
    }
  ) {
    return this.tokensService.rewardUser(rewardDto.userId, rewardDto.amount, rewardDto.reason, rewardDto.txHash);
  }

  @Post('tokens/reward-upload')
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth()
  @ApiOperation({ summary: 'Reward user for uploading content (10 HHCW)' })
  @ApiResponse({ status: 200, description: 'Upload reward distributed' })
  async rewardUpload(@Body() body: { userId: string }) {
    return this.tokensService.rewardUpload(body.userId);
  }

  @Post('tokens/reward-view')
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth()
  @ApiOperation({ summary: 'Reward user for viewing content (1 HHCW)' })
  @ApiResponse({ status: 200, description: 'View reward distributed' })
  async rewardView(@Body() body: { userId: string }) {
    return this.tokensService.rewardView(body.userId);
  }

  @Post('tokens/reward-referral')
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth()
  @ApiOperation({ summary: 'Reward user for successful referral (50 HHCW)' })
  @ApiResponse({ status: 200, description: 'Referral reward distributed' })
  async rewardReferral(@Body() body: { userId: string }) {
    return this.tokensService.rewardReferral(body.userId);
  }

  @Post('tokens/check-badges')
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth()
  @ApiOperation({ summary: 'Check user achievements and grant badges' })
  @ApiResponse({ status: 200, description: 'Badges checked and granted' })
  async checkBadges(@Body() body: { userId: string }) {
    return this.tokensService.checkAndGrantBadges(body.userId);
  }

  @Post('tokens/grant-badge')
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth()
  @ApiOperation({ summary: 'Grant a specific badge to a user' })
  @ApiResponse({ status: 200, description: 'Badge granted' })
  async grantBadge(@Body() body: { userId: string; badgeType: string }) {
    return this.tokensService.grantBadge(body.userId, body.badgeType);
  }

  @Get('users/:userId/badges')
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth()
  @ApiOperation({ summary: 'Get all badges owned by a user' })
  @ApiParam({ name: 'userId', description: 'User ID' })
  @ApiResponse({ status: 200, description: 'User badges' })
  async getUserBadges(@Param('userId') userId: string) {
    return this.tokensService.getUserBadges(userId);
  }

  @Get('badges/:tokenId')
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth()
  @ApiOperation({ summary: 'Get badge metadata' })
  @ApiParam({ name: 'tokenId', description: 'Badge token ID' })
  @ApiResponse({ status: 200, description: 'Badge metadata' })
  async getBadgeMetadata(@Param('tokenId') tokenId: string) {
    return this.tokensService.getBadgeMetadata(tokenId);
  }
}
