// Generated by Kiro
import { Controller, Post, Body, Get, Param, Query, UseGuards } from '@nestjs/common';
import { ApiTags, ApiOperation, ApiResponse, ApiBearerAuth, ApiParam, ApiQuery } from '@nestjs/swagger';

import { JwtAuthGuard } from '../auth/guards/jwt-auth.guard';

import { TokensService } from './tokens.service';

@ApiTags('tokens')
@Controller()
export class TokensController {
  constructor(private readonly tokensService: TokensService) {}

  @Get('users/:did/balance')
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth()
  @ApiOperation({ summary: 'Get user token balance' })
  @ApiParam({ name: 'did', description: 'User DID' })
  @ApiResponse({
    status: 200,
    description: 'User token balance',
    schema: {
      properties: {
        userId: { type: 'string' },
        did: { type: 'string' },
        username: { type: 'string' },
        balance: { type: 'number' },
        transactionCount: { type: 'number' },
      },
    },
  })
  @ApiResponse({ status: 404, description: 'User not found' })
  async getBalance(@Param('did') did: string) {
    return this.tokensService.getBalance(did);
  }

  @Get('users/:did/transactions')
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth()
  @ApiOperation({ summary: 'Get user transaction history' })
  @ApiParam({ name: 'did', description: 'User DID' })
  @ApiQuery({ name: 'limit', required: false, type: Number })
  @ApiQuery({ name: 'offset', required: false, type: Number })
  @ApiResponse({ status: 200, description: 'Transaction history' })
  @ApiResponse({ status: 404, description: 'User not found' })
  async getTransactions(
    @Param('did') did: string,
    @Query('limit') limit?: number,
    @Query('offset') offset?: number
  ) {
    return this.tokensService.getTransactions(
      did,
      limit ? Number(limit) : undefined,
      offset ? Number(offset) : undefined
    );
  }

  @Post('tokens/reward')
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth()
  @ApiOperation({ summary: 'Reward user with tokens (internal)' })
  @ApiResponse({ status: 200, description: 'Tokens rewarded' })
  async reward(
    @Body()
    rewardDto: {
      userId: string;
      amount: number;
      reason: string;
      txHash?: string;
    }
  ) {
    return this.tokensService.rewardUser(rewardDto.userId, rewardDto.amount, rewardDto.reason, rewardDto.txHash);
  }
}
