// Generated by Kiro - DeployAgent Entry Point
import dotenv from 'dotenv';
import DeployAgentServer from './server';

// Load environment variables
dotenv.config();

const PORT = parseInt(process.env.PORT || '3005');

// Start server
const server = new DeployAgentServer(PORT);
server.start();

// Graceful shutdown
process.on('SIGTERM', () => {
  console.log('SIGTERM signal received: closing HTTP server');
  process.exit(0);
});

process.on('SIGINT', () => {
  console.log('SIGINT signal received: closing HTTP server');
  process.exit(0);
});
