// Generated by Kiro - HauntedAI DeployAgent Types

export interface DeployRequest {
  codeCid: string;
  roomId: string;
  projectName?: string;
}

export interface DeployResponse {
  success: boolean;
  deploymentUrl?: string;
  deploymentId?: string;
  error?: string;
}

export interface VercelDeployment {
  id: string;
  url: string;
  name: string;
  state: 'BUILDING' | 'READY' | 'ERROR' | 'CANCELED';
  readyState: 'QUEUED' | 'BUILDING' | 'READY' | 'ERROR' | 'CANCELED';
  created: number;
}

export interface VercelDeploymentResponse {
  id: string;
  url: string;
  name: string;
  readyState: string;
}

export interface IPFSContent {
  content: string;
  filename: string;
}
