// Generated by Kiro
import { Module } from '@nestjs/common';
import { AuthModule } from './modules/auth/auth.module';
import { RoomsModule } from './modules/rooms/rooms.module';
import { AssetsModule } from './modules/assets/assets.module';
import { TokensModule } from './modules/tokens/tokens.module';
import { UsersModule } from './modules/users/users.module';
import { PrismaModule } from './prisma/prisma.module';
import { HealthController } from './health.controller';

@Module({
  imports: [
    PrismaModule,
    AuthModule,
    RoomsModule,
    AssetsModule,
    TokensModule,
    UsersModule,
  ],
  controllers: [HealthController],
})
export class AppModule {}
