// Generated by Kiro
import { Module } from '@nestjs/common';

import { HealthController } from './health.controller';
import { AssetsModule } from './modules/assets/assets.module';
import { AuthModule } from './modules/auth/auth.module';
import { RoomsModule } from './modules/rooms/rooms.module';
import { TokensModule } from './modules/tokens/tokens.module';
import { UsersModule } from './modules/users/users.module';
import { PrismaModule } from './prisma/prisma.module';
import { LoggerModule } from './common/logger/logger.module';
import { MetricsModule } from './common/metrics/metrics.module';
import { WebhookModule } from './common/webhook/webhook.module';

@Module({
  imports: [
    PrismaModule,
    LoggerModule,
    MetricsModule,
    WebhookModule,
    AuthModule,
    RoomsModule,
    AssetsModule,
    TokensModule,
    UsersModule,
  ],
  controllers: [HealthController],
})
export class AppModule {}
