// Generated by Kiro
import { Controller, Get } from '@nestjs/common';
import { ApiTags, ApiOperation } from '@nestjs/swagger';

@ApiTags('health')
@Controller('health')
export class HealthController {
  @Get()
  @ApiOperation({ summary: 'Health check endpoint' })
  check() {
    return {
      status: 'ok',
      service: 'HauntedAI API Gateway',
      timestamp: new Date().toISOString(),
      version: '1.0.0',
      modules: {
        auth: 'ready',
        rooms: 'ready',
        assets: 'ready',
        tokens: 'ready',
        users: 'ready',
      },
    };
  }
}
