// Generated by Kiro
import { Controller, Post, Body } from '@nestjs/common';
import { ApiTags, ApiOperation, ApiResponse } from '@nestjs/swagger';
import { AuthService } from './auth.service';

@ApiTags('auth')
@Controller('auth')
export class AuthController {
  constructor(private readonly authService: AuthService) {}

  @Post('login')
  @ApiOperation({ summary: 'Web3 wallet authentication' })
  @ApiResponse({ status: 200, description: 'JWT token issued' })
  @ApiResponse({ status: 401, description: 'Invalid signature' })
  async login(@Body() loginDto: any) {
    // TODO: Implement Web3 signature verification
    return { message: 'Auth endpoint - to be implemented' };
  }
}
