// Generated by Kiro - Integration Test
import { Test, TestingModule } from '@nestjs/testing';
import { JwtService } from '@nestjs/jwt';
import { UnauthorizedException } from '@nestjs/common';

import { AuthService } from './auth.service';
import { PrismaService } from '../../prisma/prisma.service';

describe('AuthService - Integration Tests', () => {
  let service: AuthService;
  let prismaService: PrismaService;
  let jwtService: JwtService;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        AuthService,
        {
          provide: PrismaService,
          useValue: {
            user: {
              findUnique: jest.fn(),
              create: jest.fn(),
            },
          },
        },
        {
          provide: JwtService,
          useValue: {
            sign: jest.fn(),
          },
        },
      ],
    }).compile();

    service = module.get<AuthService>(AuthService);
    prismaService = module.get<PrismaService>(PrismaService);
    jwtService = module.get<JwtService>(JwtService);
  });

  describe('verifySignature', () => {
    it('should verify a valid Web3 signature', async () => {
      // Real example from ethers.js documentation
      const walletAddress = '0x14791697260E4c9A71f18484C9f997B308e59325';
      const message = 'Hello World';
      const signature =
        '0x8b9b9c4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e';

      // Note: This will fail with the dummy signature, but tests the flow
      const result = await service.verifySignature(walletAddress, message, signature);

      expect(typeof result).toBe('boolean');
    });

    it('should return false for invalid signature', async () => {
      const walletAddress = '0x14791697260E4c9A71f18484C9f997B308e59325';
      const message = 'Hello World';
      const invalidSignature = '0xinvalid';

      const result = await service.verifySignature(walletAddress, message, invalidSignature);

      expect(result).toBe(false);
    });
  });

  describe('login', () => {
    it('should create new user and return JWT for valid signature', async () => {
      const loginDto = {
        walletAddress: '0x1234567890123456789012345678901234567890',
        message: 'Sign this message to authenticate',
        signature: '0xvalidsignature',
      };

      // Mock signature verification
      jest.spyOn(service, 'verifySignature').mockResolvedValue(true);

      // Mock user not found
      jest.spyOn(prismaService.user, 'findUnique').mockResolvedValue(null);

      // Mock user creation
      const mockUser = {
        id: 'user-123',
        did: 'did:ethr:0x1234567890123456789012345678901234567890',
        username: 'user_123456',
        walletAddress: '0x1234567890123456789012345678901234567890',
        createdAt: new Date(),
        updatedAt: new Date(),
      };
      jest.spyOn(prismaService.user, 'create').mockResolvedValue(mockUser);

      // Mock JWT generation
      jest.spyOn(jwtService, 'sign').mockReturnValue('mock-jwt-token');

      const result = await service.login(loginDto);

      expect(result).toHaveProperty('accessToken');
      expect(result).toHaveProperty('user');
      expect(result.accessToken).toBe('mock-jwt-token');
      expect(result.user.id).toBe('user-123');
      expect(result.user.walletAddress).toBe(loginDto.walletAddress);
    });

    it('should return existing user and JWT for valid signature', async () => {
      const loginDto = {
        walletAddress: '0x1234567890123456789012345678901234567890',
        message: 'Sign this message to authenticate',
        signature: '0xvalidsignature',
      };

      // Mock signature verification
      jest.spyOn(service, 'verifySignature').mockResolvedValue(true);

      // Mock existing user
      const mockUser = {
        id: 'existing-user-123',
        did: 'did:ethr:0x1234567890123456789012345678901234567890',
        username: 'existing_user',
        walletAddress: '0x1234567890123456789012345678901234567890',
        createdAt: new Date(),
        updatedAt: new Date(),
      };
      jest.spyOn(prismaService.user, 'findUnique').mockResolvedValue(mockUser);

      // Mock JWT generation
      jest.spyOn(jwtService, 'sign').mockReturnValue('mock-jwt-token-existing');

      const result = await service.login(loginDto);

      expect(result).toHaveProperty('accessToken');
      expect(result.accessToken).toBe('mock-jwt-token-existing');
      expect(result.user.id).toBe('existing-user-123');
      expect(result.user.username).toBe('existing_user');
    });

    it('should throw UnauthorizedException for invalid signature', async () => {
      const loginDto = {
        walletAddress: '0x1234567890123456789012345678901234567890',
        message: 'Sign this message to authenticate',
        signature: '0xinvalidsignature',
      };

      // Mock signature verification to fail
      jest.spyOn(service, 'verifySignature').mockResolvedValue(false);

      await expect(service.login(loginDto)).rejects.toThrow(UnauthorizedException);
      await expect(service.login(loginDto)).rejects.toThrow('Invalid signature');
    });
  });

  describe('validateUser', () => {
    it('should return user for valid userId', async () => {
      const mockUser = {
        id: 'user-123',
        did: 'did:ethr:0x1234567890123456789012345678901234567890',
        username: 'test_user',
        walletAddress: '0x1234567890123456789012345678901234567890',
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      jest.spyOn(prismaService.user, 'findUnique').mockResolvedValue(mockUser);

      const result = await service.validateUser('user-123');

      expect(result).toEqual(mockUser);
      expect(result.id).toBe('user-123');
    });

    it('should throw UnauthorizedException for invalid userId', async () => {
      jest.spyOn(prismaService.user, 'findUnique').mockResolvedValue(null);

      await expect(service.validateUser('invalid-id')).rejects.toThrow(
        UnauthorizedException
      );
      await expect(service.validateUser('invalid-id')).rejects.toThrow('User not found');
    });
  });
});
