// Generated by Kiro
import { Injectable, UnauthorizedException } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import { ethers } from 'ethers';

import { PrismaService } from '../../prisma/prisma.service';

import { LoginDto } from './dto/login.dto';

@Injectable()
export class AuthService {
  constructor(
    private prisma: PrismaService,
    private jwtService: JwtService
  ) {}

  async login(loginDto: LoginDto) {
    const { walletAddress, signature, message } = loginDto;

    // Verify Web3 signature
    const isValid = await this.verifySignature(walletAddress, message, signature);

    if (!isValid) {
      throw new UnauthorizedException('Invalid signature');
    }

    // Find or create user
    let user = await this.prisma.user.findUnique({
      where: { walletAddress: walletAddress.toLowerCase() },
    });

    if (!user) {
      // Create new user
      user = await this.prisma.user.create({
        data: {
          did: `did:ethr:${walletAddress.toLowerCase()}`,
          username: `user_${walletAddress.slice(2, 8)}`,
          walletAddress: walletAddress.toLowerCase(),
        },
      });
    }

    // Generate JWT token
    const payload = {
      sub: user.id,
      did: user.did,
      walletAddress: user.walletAddress,
    };

    const accessToken = this.jwtService.sign(payload);

    return {
      accessToken,
      user: {
        id: user.id,
        did: user.did,
        username: user.username,
        walletAddress: user.walletAddress,
      },
    };
  }

  async verifySignature(
    walletAddress: string,
    message: string,
    signature: string
  ): Promise<boolean> {
    try {
      // Recover the address from the signature
      const recoveredAddress = ethers.verifyMessage(message, signature);

      // Compare addresses (case-insensitive)
      return recoveredAddress.toLowerCase() === walletAddress.toLowerCase();
    } catch (error) {
      console.error('Signature verification error:', error);
      return false;
    }
  }

  async validateUser(userId: string) {
    const user = await this.prisma.user.findUnique({
      where: { id: userId },
    });

    if (!user) {
      throw new UnauthorizedException('User not found');
    }

    return user;
  }
}
