// Generated by Kiro - CodeAgent Entry Point
import dotenv from 'dotenv';
import { startServer } from './server';

// Load environment variables
dotenv.config();

// Validate required environment variables
if (!process.env.OPENAI_API_KEY) {
  console.error('ERROR: OPENAI_API_KEY environment variable is required');
  process.exit(1);
}

// Start the server
startServer();
