// Generated by Kiro - CodeAgent Express Server
import express, { Request, Response } from 'express';
import cors from 'cors';
import { CodeService } from './code.service';
import { CodeGenerationRequest } from './types';

const app = express();
const PORT = process.env.PORT || 3004;

// Middleware
app.use(cors());
app.use(express.json({ limit: '10mb' }));

// Initialize service
const codeService = new CodeService();

/**
 * Health check endpoint
 */
app.get('/health', (req: Request, res: Response) => {
  res.json({
    status: 'ok',
    service: 'code-agent',
    timestamp: new Date().toISOString(),
  });
});

/**
 * POST /generate - Generate mini-game code
 */
app.post('/generate', async (req: Request, res: Response) => {
  try {
    const request: CodeGenerationRequest = req.body;

    // Validate request
    if (!request.story || typeof request.story !== 'string') {
      return res.status(400).json({
        error: 'Invalid request: story is required and must be a string',
      });
    }

    if (!request.imageTheme || typeof request.imageTheme !== 'string') {
      return res.status(400).json({
        error: 'Invalid request: imageTheme is required and must be a string',
      });
    }

    console.log('Received code generation request');
    console.log(`Story length: ${request.story.length}`);
    console.log(`Image theme: ${request.imageTheme}`);

    // Generate code
    const result = await codeService.generateCode(request);

    console.log('Code generation completed successfully');
    console.log(`CID: ${result.cid}`);
    console.log(`Patch attempts: ${result.patchAttempts || 0}`);

    res.json(result);
  } catch (error) {
    console.error('Code generation failed:', error);

    res.status(500).json({
      error: 'Code generation failed',
      message: (error as Error).message,
    });
  }
});

/**
 * Start server
 */
export function startServer(): void {
  app.listen(PORT, () => {
    console.log(`🎮 CodeAgent server running on port ${PORT}`);
    console.log(`Health check: http://localhost:${PORT}/health`);
    console.log(`Generate endpoint: POST http://localhost:${PORT}/generate`);
  });
}

export default app;
