// Generated by Kiro - CodeAgent Express Server
import express, { Request, Response, NextFunction } from 'express';
import cors from 'cors';
import { CodeService } from './code.service';
import { AgentMetrics } from '@hauntedai/shared';
import { CodeGenerationRequest } from './types';

export class CodeAgentServer {
  private app: express.Application;
  private codeService: CodeService;
  private metrics: AgentMetrics;
  private port: number;

  constructor(port: number = 3004) {
    this.app = express();
    this.port = port;
    this.codeService = new CodeService();
    this.metrics = new AgentMetrics('code');
    this.setupMiddleware();
    this.setupRoutes();
    this.setupErrorHandling();
  }

  private setupMiddleware(): void {
    this.app.use(cors());
    this.app.use(express.json({ limit: '10mb' }));

    // Request logging and metrics
    this.app.use((req: Request, res: Response, next: NextFunction) => {
      const startTime = Date.now();
      console.log(`[${new Date().toISOString()}] ${req.method} ${req.path}`);
      
      res.on('finish', () => {
        const duration = (Date.now() - startTime) / 1000;
        this.metrics.recordHttpRequest(req.method, req.path, res.statusCode, duration);
      });
      
      next();
    });
  }

  private setupRoutes(): void {

    // Health check endpoint
    this.app.get('/health', (req: Request, res: Response) => {
      res.json({
        status: 'ok',
        service: 'code-agent',
        timestamp: new Date().toISOString(),
      });
    });

    // Code generation endpoint
    this.app.post('/generate', async (req: Request, res: Response, next: NextFunction) => {
      const startTime = Date.now();
      try {
        const request: CodeGenerationRequest = req.body;

        // Validate request
        if (!request.story || typeof request.story !== 'string') {
          return res.status(400).json({
            error: 'Invalid request: story is required and must be a string',
          });
        }

        if (!request.imageTheme || typeof request.imageTheme !== 'string') {
          return res.status(400).json({
            error: 'Invalid request: imageTheme is required and must be a string',
          });
        }

        console.log('Received code generation request');
        console.log(`Story length: ${request.story.length}`);
        console.log(`Image theme: ${request.imageTheme}`);

        // Generate code
        const result = await this.codeService.generateCode(request);

        const duration = (Date.now() - startTime) / 1000;
        this.metrics.recordExecution('code', 'success', duration);

        console.log('Code generation completed successfully');
        console.log(`CID: ${result.cid}`);
        console.log(`Patch attempts: ${result.patchAttempts || 0}`);

        res.json(result);
      } catch (error) {
        const duration = (Date.now() - startTime) / 1000;
        this.metrics.recordExecution('code', 'failure', duration);
        this.metrics.recordFailure('code', error.name || 'UnknownError');
        next(error);
      }
    });

    // Metrics endpoint
    this.app.get('/metrics', async (req: Request, res: Response) => {
      try {
        const metrics = await this.metrics.getMetrics();
        res.set('Content-Type', this.metrics.getContentType());
        res.send(metrics);
      } catch (error) {
        res.status(500).json({ error: 'Failed to get metrics' });
      }
    });

    // Root endpoint
    this.app.get('/', (req: Request, res: Response) => {
      res.json({
        service: 'code-agent',
        version: '1.0.0',
        status: 'running',
        endpoints: {
          health: 'GET /health',
          generate: 'POST /generate',
          metrics: 'GET /metrics',
        },
      });
    });
  }

  private setupErrorHandling(): void {
    // 404 handler
    this.app.use((req: Request, res: Response) => {
      res.status(404).json({
        error: 'Not Found',
        message: `Route ${req.method} ${req.path} not found`,
        statusCode: 404,
        timestamp: new Date().toISOString(),
      });
    });

    // Global error handler
    this.app.use((err: Error, req: Request, res: Response, next: NextFunction) => {
      console.error('Error:', err);

      const statusCode = (err as any).statusCode || 500;
      res.status(statusCode).json({
        error: err.name || 'Internal Server Error',
        message: err.message || 'An unexpected error occurred',
        statusCode,
        timestamp: new Date().toISOString(),
      });
    });
  }

  public start(): void {
    this.app.listen(this.port, () => {
      console.log(`🎮 CodeAgent server running on port ${this.port}`);
      console.log(`📍 Health check: http://localhost:${this.port}/health`);
      console.log(`📍 Generate code: POST http://localhost:${this.port}/generate`);
    });
  }

  public getApp(): express.Application {
    return this.app;
  }
}

// Legacy export for backward compatibility
export function startServer(): void {
  const server = new CodeAgentServer();
  server.start();
}

export default CodeAgentServer;
