// Generated by Kiro - CodeAgent Types

export interface CodeGenerationRequest {
  story: string;
  imageTheme: string;
  roomId?: string;
}

export interface CodeGenerationResponse {
  code: string;
  cid: string;
  tested: boolean;
  patchAttempts?: number;
}

export interface CodeTestResult {
  passed: boolean;
  errors: string[];
  warnings: string[];
}

export interface CodePatchRequest {
  code: string;
  errors: string[];
}

export interface CodePatchResponse {
  patchedCode: string;
  changes: string;
}
