// Generated by Kiro
import { Injectable } from '@nestjs/common';
import { LoggerService } from '../logger/logger.service';

export interface WebhookPayload {
  event: string;
  severity: 'critical' | 'error' | 'warning';
  message: string;
  error?: {
    name: string;
    message: string;
    stack?: string;
  };
  metadata?: Record<string, any>;
  timestamp: string;
  service: string;
}

@Injectable()
export class WebhookService {
  private readonly webhookUrl: string;
  private readonly enabled: boolean;

  constructor(private readonly logger: LoggerService) {
    this.webhookUrl = process.env.ERROR_WEBHOOK_URL || '';
    this.enabled = !!this.webhookUrl;

    if (!this.enabled) {
      this.logger.warn('Webhook notifications disabled - no ERROR_WEBHOOK_URL configured', 'WebhookService');
    }
  }

  async sendCriticalError(
    event: string,
    error: Error,
    metadata?: Record<string, any>
  ): Promise<void> {
    if (!this.enabled) {
      return;
    }

    const payload: WebhookPayload = {
      event,
      severity: 'critical',
      message: error.message,
      error: {
        name: error.name,
        message: error.message,
        stack: error.stack,
      },
      metadata,
      timestamp: new Date().toISOString(),
      service: 'HauntedAI API Gateway',
    };

    await this.sendWebhook(payload);
  }

  async sendError(
    event: string,
    message: string,
    metadata?: Record<string, any>
  ): Promise<void> {
    if (!this.enabled) {
      return;
    }

    const payload: WebhookPayload = {
      event,
      severity: 'error',
      message,
      metadata,
      timestamp: new Date().toISOString(),
      service: 'HauntedAI API Gateway',
    };

    await this.sendWebhook(payload);
  }

  async sendWarning(
    event: string,
    message: string,
    metadata?: Record<string, any>
  ): Promise<void> {
    if (!this.enabled) {
      return;
    }

    const payload: WebhookPayload = {
      event,
      severity: 'warning',
      message,
      metadata,
      timestamp: new Date().toISOString(),
      service: 'HauntedAI API Gateway',
    };

    await this.sendWebhook(payload);
  }

  private async sendWebhook(payload: WebhookPayload): Promise<void> {
    try {
      const response = await fetch(this.webhookUrl, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'User-Agent': 'HauntedAI-Webhook/1.0',
        },
        body: JSON.stringify(payload),
      });

      if (!response.ok) {
        throw new Error(`Webhook request failed with status ${response.status}`);
      }

      this.logger.log(
        `Webhook notification sent: ${payload.event} (${payload.severity})`,
        'WebhookService'
      );
    } catch (error) {
      // Don't throw - we don't want webhook failures to break the application
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      this.logger.error(
        `Failed to send webhook notification: ${errorMessage}`,
        error instanceof Error ? error.stack : undefined,
        'WebhookService'
      );
    }
  }

  isEnabled(): boolean {
    return this.enabled;
  }
}
