// Generated by Kiro
import { Module } from '@nestjs/common';
import { WebhookService } from './webhook.service';
import { LoggerModule } from '../logger/logger.module';

@Module({
  imports: [LoggerModule],
  providers: [WebhookService],
  exports: [WebhookService],
})
export class WebhookModule {}
