// Generated by Kiro
// Managed by Kiro - CID Metadata Service

import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { StorachaService } from './storacha.service';

/**
 * CID Metadata Service
 * Handles storage and retrieval of CID metadata in the database
 * 
 * Features:
 * - Save CID metadata to database
 * - Track file type, size, and timestamp
 * - Validate CID format
 * 
 * Requirements: 7.3
 */
@Injectable()
export class MetadataService {
  private readonly logger = new Logger(MetadataService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly storachaService: StorachaService,
  ) {}

  /**
   * Save CID metadata to database
   * Requirement 7.3: Save CID metadata with file type, size, and timestamp
   * 
   * @param roomId - Room ID
   * @param agentType - Type of agent that generated the content
   * @param cid - Content Identifier
   * @param fileType - File type (e.g., 'text/plain', 'image/png')
   * @param fileSize - File size in bytes
   * @param metadata - Additional metadata as JSON
   * @returns Created asset record
   */
  async saveCIDMetadata(
    roomId: string,
    agentType: 'story' | 'asset' | 'code' | 'deploy',
    cid: string,
    fileType: string,
    fileSize: number,
    metadata?: Record<string, any>,
  ) {
    // Validate CID format
    if (!this.storachaService.validateCID(cid)) {
      throw new Error(`Invalid CID format: ${cid}`);
    }

    this.logger.log(
      `Saving CID metadata: ${cid} (${agentType}, ${fileType}, ${fileSize} bytes)`
    );

    try {
      const asset = await this.prisma.asset.create({
        data: {
          roomId,
          agentType,
          cid,
          fileType,
          fileSize,
          metadata: metadata ? JSON.stringify(metadata) : undefined,
        },
      });

      this.logger.log(`CID metadata saved successfully: ${asset.id}`);
      return asset;
    } catch (error) {
      const err = error as Error;
      this.logger.error(`Failed to save CID metadata: ${err.message}`, error);
      throw error;
    }
  }

  /**
   * Get CID metadata from database
   * 
   * @param cid - Content Identifier
   * @returns Asset record with metadata
   */
  async getCIDMetadata(cid: string) {
    this.logger.log(`Retrieving CID metadata: ${cid}`);

    const asset = await this.prisma.asset.findFirst({
      where: { cid },
      include: {
        room: {
          include: {
            owner: {
              select: {
                id: true,
                username: true,
                did: true,
              },
            },
          },
        },
      },
    });

    if (!asset) {
      throw new Error(`CID not found: ${cid}`);
    }

    return {
      ...asset,
      metadata: asset.metadata ? JSON.parse(asset.metadata as string) : null,
    };
  }

  /**
   * Get all assets for a room
   * 
   * @param roomId - Room ID
   * @returns Array of asset records
   */
  async getRoomAssets(roomId: string) {
    this.logger.log(`Retrieving assets for room: ${roomId}`);

    const assets = await this.prisma.asset.findMany({
      where: { roomId },
      orderBy: { createdAt: 'asc' },
    });

    return assets.map(asset => ({
      ...asset,
      metadata: asset.metadata ? JSON.parse(asset.metadata as string) : null,
    }));
  }

  /**
   * Upload file and save metadata in one operation
   * Convenience method that combines upload and metadata storage
   * 
   * @param roomId - Room ID
   * @param agentType - Type of agent
   * @param buffer - File content
   * @param filename - File name
   * @param fileType - MIME type
   * @param metadata - Additional metadata
   * @returns Object with CID and asset record
   */
  async uploadAndSaveMetadata(
    roomId: string,
    agentType: 'story' | 'asset' | 'code' | 'deploy',
    buffer: Buffer,
    filename: string,
    fileType: string,
    metadata?: Record<string, any>,
  ) {
    this.logger.log(`Uploading file and saving metadata: ${filename}`);

    // Upload to Storacha
    const cid = await this.storachaService.uploadFile(buffer, filename);

    // Save metadata to database
    const asset = await this.saveCIDMetadata(
      roomId,
      agentType,
      cid,
      fileType,
      buffer.length,
      metadata,
    );

    return { cid, asset };
  }

  /**
   * Validate CID format using regex
   * Requirement 7.3: Implement CID validation
   * 
   * @param cid - CID string to validate
   * @returns true if valid, false otherwise
   */
  validateCID(cid: string): boolean {
    return this.storachaService.validateCID(cid);
  }
}
