// Generated by Kiro
// Managed by Kiro - Storacha Module

import { Module } from '@nestjs/common';
import { StorachaService } from './storacha.service';
import { MetadataService } from './metadata.service';
import { FallbackStorageService } from './fallback-storage.service';
import { PrismaModule } from '../../prisma/prisma.module';

@Module({
  imports: [PrismaModule],
  providers: [StorachaService, MetadataService, FallbackStorageService],
  exports: [StorachaService, MetadataService, FallbackStorageService],
})
export class StorachaModule {}
